### ISSUE TITLE
BE array serialization broken

### ISSUE THREAD

**Issue by mdavidsaver** [epics-base/pvDataCPP#65]
The fix for #54 introduced a regression to ByteBuffer effecting serialization to big endian.  The bug appears when an array is serialized by a BE peer, or from a BE peer.  The effect is an out of bounds array access.

**Comment by mdavidsaver** [comment]
Thanks to @hjunkes for reporting and identifying the cause.

https://epics.anl.gov/tech-talk/2019/msg00571.php

**Comment by mdavidsaver** [comment]
Added test coverage with 5525119778bcefdbe53103a1c07984c0d7fae112 and fixed with 8f0111e482aa139f4311378f2b0bc831c46420b2

**Comment by hjunkes** [comment]
I have tested the fix on RTEMS - 5 PowerPc
It worked. The test also worked.

**Comment by mdavidsaver** [comment]
Re-opening until this fix is included in a release.

**Comment by mdavidsaver** [comment]
Released in module version 8.0.0, included in EPICS 7.0.3
