### ISSUE TITLE
get operation on softIOC pv don't return timeStamp field

### ISSUE THREAD

**Issue by bisegni** [epics-base/pvDataCPP#83]
Hello EPICS group
I'm working with last epics release and I have notice that making a get operation for an IOC using a CA provider for crete a pvac::ClientChannel I don't receive the timestamp field:

I noticed that also the official caget has the problem:

developer@e058f4bc2090:/workspace$ pvget variable:sum
variable:sum 2023-05-05 16:34:54.607  3
developer@e058f4bc2090:/workspace$ caget variable:sum
variable:sum                   3

so is a client library problem or a server or something else?

**Comment by mdavidsaver** [comment]
see discussion of https://epics.anl.gov/tech-talk/2023/msg00657.php

**Comment by bisegni** [comment]
hi @mdavidsaver, yes he's me. But definitely what could be an effective way to fetch all the information for an PV using CA provider?  could be the best solution, launch two monitor that listen on different fields of the same pv and reassemble the structure on client side?
thank you
