### ISSUE TITLE
Unaligned access causing SIGBUS on Raspbian

### ISSUE THREAD

**Issue by CubicTec** [epics-base/pvDataCPP#84]
Hardware: Respberry Pi 4B
OS: Raspbian GNU/Linux 11 (bullseye)
EPICS version：7.0.5、7.0.6.1、7.0.7

I built an IOC application with a simple db file:

> #scale.db
record(calc,"Scale$(N)"){
    field(INPA,"Scale$(N).VAL")
    field(CALC,"A+1")
    field(SCAN,".1 second")
}

I add pvAccess Server in the App/src/Makefile

> #Link QSRV (pvAccess Server) if available
> ifdef EPICS_QSRV_MAJOR_VERSION
>     siocScle_LIBS += qsrv
>     siocScle_LIBS += $(EPICS_BASE_PVA_CORE_LIBS)
>     siocScle_DBD += PVAServerRegister.dbd
>     siocScle_DBD += qsrv.dbd
> endif

After `make` I run the ioc app and I can caget the channel for example Scale1. But when I use pvget the terminal running the ioc above  exit the last message is `epics> Bus error`

**Comment by CubicTec** [comment]
I am using the official Raspberry Pi OS release.

> Linux raspberrypi 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux

 Unfortunately I can't check the alignment.
<img width="665" alt="微信截图_20230525161904" src="https://github.com/epics-base/pvDataCPP/assets/59425014/545971ad-7fd6-4a1c-b966-b2d4b98cce53">

**Comment by mdavidsaver** [comment]
Ah, you are running a 64-bit (aarch64) kernel, while my pi3 has 32-bit (armv7l).  This certainly explains the absence of [`/proc/cpu/alignment`](https://github.com/raspberrypi/linux/issues/2283), and probably the difference in alignment handling as well.

Anyway, I've merged a fix (#85) which should have the same effect as the patch which you tested.

Thank you for reporting this!

**Comment by CubicTec** [comment]
> I'm gonna check if it runs well on my colleague's Macbook with M1.
> 
> > It works. I can pvget/pvmonitor now. Thank you!!!
> > > Could you try making this change? Then re-run `make` for epics-base and re-test.
> > > ```diff
> > > diff --git a/modules/pvData/src/misc/pv/byteBuffer.h b/modules/pvData/src/misc/pv/byteBuffer.h
> > > index e507f15..4a71c8a 100644
> > > --- a/modules/pvData/src/misc/pv/byteBuffer.h
> > > +++ b/modules/pvData/src/misc/pv/byteBuffer.h
> > > @@ -157,7 +157,7 @@ struct swap<8> {
> > >   * in execution time and/or object code size of byte-wise copy.
> > >   */
> > >  
> > > -#ifdef _ARCH_PPC
> > > +#if defined(_ARCH_PPC) || defined(__arm__) || defined(_M_ARM)
> > >  
> > >  template<typename T>
> > >  union alignu {
> > > ```

Still works well on M1

**Comment by CubicTec** [comment]
> Ah, you are running a 64-bit (aarch64) kernel, while my pi3 has 32-bit (armv7l). This certainly explains the absence of [`/proc/cpu/alignment`](https://github.com/raspberrypi/linux/issues/2283), and probably the difference in alignment handling as well.
> 
> Anyway, I've merged a fix (#85) which should have the same effect as the patch which you tested.
> 
> Thank you for reporting this!

Glad to help！
